# Generated by Django 4.2.7 on 2023-11-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=None),
        ),
    ]
